[package]
name = "teo-ffi"
description = "FFI for interacting with Teo."
version = "0.0.1"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
